

spring:
  application:
    name: busiess
  profiles:
    active: default

  cloud:
    config:
    enabled: true

eureka:
  instance:
  preferIpAdddress: true
  client:
    registryWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
